name: CI

on:
  push:
    branches: [main, develop] # CI en ramas
    tags:
      - 'v*' # dispara publish al pushear tags vX.Y.Z
  pull_request:
    branches: [main, develop]
  workflow_dispatch: # ejecución manual

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Format check
        run: yarn format

      - name: Build
        run: yarn build

      - name: Test library
        run: yarn test

  publish:
    # Solo publica con tag v* o si lo corres manualmente
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # requerido si usas --provenance

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true # <-- hace que npm use el token del entorno

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      # (Opcional) debug: confirma que el token se aplica al whoami
      - name: npm whoami (debug)
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
